const SIGNIN_RECRUITER_REQUEST_TOPIC = "signinRecruiterRequest";
const SIGNIN_RECRUITER_RESPONSE_TOPIC = "signinRecruiterResponse";
const SIGNUP_RECRUITER_REQUEST_TOPIC = "signupRecruiterRequest";
const SIGNUP_RECRUITER_RESPONSE_TOPIC = "signupRecruiterResponse";
const POST_JOB_REQUEST = "postJobRequest";
const POST_JOB_RESPONSE = "postJobResponse";
const UPLOAD_COMPANY_LOGO_REQUEST = "uploadCompanyLogoRequest";
const UPLOAD_COMPANY_LOGO_RESPONSE = "uploadCompanyLogoResponse";
const GET_JOBS_BY_RECRUITER_RESPONSE = "getJobsByRecruiterResponse";
const GET_JOBS_BY_RECRUITER_REQUEST = "getJobsByRecruiterRequest";
const SIGNUP_APPLICANT_REQUEST_TOPIC = "signupApplicantRequest";
const SIGNUP_APPLICANT_RESPONSE_TOPIC = "signupApplicantResponse";

module.exports = {
    SIGNIN_RECRUITER_REQUEST_TOPIC, SIGNIN_RECRUITER_RESPONSE_TOPIC,
    SIGNUP_RECRUITER_REQUEST_TOPIC, SIGNUP_RECRUITER_RESPONSE_TOPIC,
    POST_JOB_REQUEST, POST_JOB_RESPONSE,
    UPLOAD_COMPANY_LOGO_REQUEST, UPLOAD_COMPANY_LOGO_RESPONSE, 
    GET_JOBS_BY_RECRUITER_REQUEST, GET_JOBS_BY_RECRUITER_RESPONSE,
    SIGNUP_APPLICANT_REQUEST_TOPIC, SIGNUP_APPLICANT_RESPONSE_TOPIC,
};