const LOGIN_RECRUITER_REQUEST_TOPIC = "signinRecruiterRequest";
const LOGIN_RECRUITER_RESPONSE_TOPIC = "signinRecruiterResponse";
const SIGNUP_RECRUITER_REQUEST_TOPIC = "signupRecruiterRequest";
const SIGNUP_RECRUITER_RESPONSE_TOPIC = "signupRecruiterResponse";

module.exports = {
    LOGIN_RECRUITER_REQUEST_TOPIC, LOGIN_RECRUITER_RESPONSE_TOPIC,
    SIGNUP_RECRUITER_REQUEST_TOPIC, SIGNUP_RECRUITER_RESPONSE_TOPIC 
};