const SIGNIN_RECRUITER_REQUEST_TOPIC = "signinRecruiterRequest";
const SIGNIN_RECRUITER_RESPONSE_TOPIC = "signinRecruiterResponse";
const SIGNUP_RECRUITER_REQUEST_TOPIC = "signupRecruiterRequest";
const SIGNUP_RECRUITER_RESPONSE_TOPIC = "signupRecruiterResponse";

const SIGNIN_APPLICANT_REQUEST_TOPIC = "signinAPPLICANTRequest";
const SIGNIN_APPLICANT_RESPONSE_TOPIC = "signinAPPLICANTResponse";
const SIGNUP_APPLICANT_REQUEST_TOPIC = "signupAPPLICANTRequest";
const SIGNUP_APPLICANT_RESPONSE_TOPIC = "signupAPPLICANTResponse";

const POST_JOB_REQUEST = "postJobRequest";
const POST_JOB_RESPONSE = "postJobResponse";

const GET_JOBS_BY_RECRUITER_RESPONSE = "getJobsByRecruiterResponse";
const GET_JOBS_BY_RECRUITER_REQUEST = "getJobsByRecruiterRequest";

const POST_RECRUITER_PROFILE_REQUEST = "postRecruiterProfileRequest";
const POST_RECRUITER_PROFILE_RESPONSE = "postRecruiterProfileResponse";

const EDIT_JOB_REQUEST = "editJobRequest";
const EDIT_JOB_RESPONSE = "editJobResponse";

const UPDATE_JOB_VIEWS_REQUEST = "updateJobViewsRequest";
const UPDATE_JOB_VIEWS_RESPONSE = "updateJobViewsResponse";

const GET_RECRUITER_PROFILE_REQUEST = "getRecruiterProfileRequest";
const GET_RECRUITER_PROFILE_RESPONSE = "getRecruiterProfileResponse";

module.exports = {
    SIGNIN_RECRUITER_REQUEST_TOPIC, SIGNIN_RECRUITER_RESPONSE_TOPIC,
    SIGNUP_RECRUITER_REQUEST_TOPIC, SIGNUP_RECRUITER_RESPONSE_TOPIC,
    SIGNIN_APPLICANT_REQUEST_TOPIC, SIGNIN_APPLICANT_RESPONSE_TOPIC,
    SIGNUP_APPLICANT_REQUEST_TOPIC, SIGNUP_APPLICANT_RESPONSE_TOPIC,
    POST_JOB_REQUEST, POST_JOB_RESPONSE,
    GET_JOBS_BY_RECRUITER_REQUEST, GET_JOBS_BY_RECRUITER_RESPONSE,
    POST_RECRUITER_PROFILE_REQUEST, POST_RECRUITER_PROFILE_RESPONSE,
    EDIT_JOB_REQUEST, EDIT_JOB_RESPONSE,
    UPDATE_JOB_VIEWS_REQUEST, UPDATE_JOB_VIEWS_RESPONSE,
    GET_RECRUITER_PROFILE_REQUEST, GET_RECRUITER_PROFILE_RESPONSE
};